---
:verbose: true
:concurrency: 10
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log

:queues:
  - [the_comments_workers, 5]
  - [single, 1]

:limits:
  the_comments_workers: 5
  single: 1
